// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils
using EWSoftware.EntityFramework.DataAnnotations;

namespace EntityFrameworkNet8TestApp.Database
{
    [NeverTrack, LoadAllStoredProcedure("spCompanies")]
    public sealed class spCompaniesResult
    {
        public string CompanyName { get; set; } = null!;

    }
}
