// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils

using System.ComponentModel.DataAnnotations;

using EWSoftware.EntityFramework;
using EWSoftware.EntityFramework.DataAnnotations;

namespace EntityFrameworkNet8TestApp.Database
{
    [LoadAllStoredProcedure("spStateCodes")]
    public sealed class StateCode : ChangeTrackingEntity
    {
        public string State
        {
            get;
            set => this.SetWithNotify(value, ref field);
        } = String.Empty;

        public string StateDesc
        {
            get;
            set => this.SetWithNotify(value, ref field);
        } = String.Empty;

        /// <summary>A fake primary key</summary>
        /// <remarks>The <see cref="State"/> is the actual key but it is mutable so we can't use it for
        /// change tracking.  As a hack, we use the last modified time stamp instead.  We also can't use the
        /// insert, update, and delete stored procedure attributes for this entity.</remarks>
        [Key, Ignore(true, true)]
        public byte[] LastModified
        {
            get;
            set => this.SetWithNotify(value, ref field);
        } = [];

        [Ignore(true, true)]
        public bool IsInUse
        {
            get;
            set => this.SetWithNotify(value, ref field);
        }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <remarks>This assigns a value to the <see cref="LastModified"/> property to serve as a unique key
        /// for change tracking.</remarks>
        public StateCode()
        {
            this.LastModified = BitConverter.GetBytes(DateTime.Now.Ticks);
        }
    }
}
