// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils
//
// This code will need to be reviewed and tested to fix up any issues.

// TODO: Add or remove using statements as needed
using System;
using System.ComponentModel.DataAnnotations;

using EWSoftware.EntityFramework;
using EWSoftware.EntityFramework.DataAnnotations;

namespace EntityFrameworkNet8TestApp.Database
{
    [InsertEntityStoredProcedure("spDemoTableAddUpdate"), UpdateEntityStoredProcedure("spDemoTableAddUpdate"), DeleteEntityStoredProcedure("spDemoTableDelete")]
    public sealed class DemoTable : ChangeTrackingEntity
    {
        private int _listKey;

        [Key]
        public int ListKey
        {
            get => _listKey;
            set => this.SetWithNotify(value, ref _listKey);
        }

        private string _label;

        public string Label
        {
            get => _label;
            set => this.SetWithNotify(value, ref _label);
        }

        private string _textValue;

        public string TextValue
        {
            get => _textValue;
            set => this.SetWithNotify(value, ref _textValue);
        }

        private DateTime _dateValue;

        public DateTime DateValue
        {
            get => _dateValue;
            set => this.SetWithNotify(value, ref _dateValue);
        }

        private bool _boolValue;

        public bool BoolValue
        {
            get => _boolValue;
            set => this.SetWithNotify(value, ref _boolValue);
        }

        private byte[] _lastModified;

        [Ignore(true, true)]
        public byte[] LastModified
        {
            get => _lastModified;
            set => this.SetWithNotify(value, ref _lastModified);
        }

    }
}
