// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils
//
// This code will need to be reviewed and tested to fix up any issues.

// TODO: Add or remove using statements as needed
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using EWSoftware.EntityFramework;
using EWSoftware.EntityFramework.DataAnnotations;

namespace EntityFrameworkNet48TestApp.Database
{
    // TODO: Check Database\StateCode.cs for additional code for the entity
    [InsertEntityStoredProcedure("spStateCodeAddUpdate"), UpdateEntityStoredProcedure("spStateCodeAddUpdate"), DeleteEntityStoredProcedure("spStateCodeDelete")]
    public sealed class StateCode : ChangeTrackingEntity
    {
        private string _state;

        public string State
        {
            get => _state;
            set => this.SetWithNotify(value, ref _state);
        }

        private string _stateDesc;

        public string StateDesc
        {
            get => _stateDesc;
            set => this.SetWithNotify(value, ref _stateDesc);
        }

        private byte[] _lastModified;

        [Key, Ignore(true, true)]
        public byte[] LastModified
        {
            get => _lastModified;
            set => this.SetWithNotify(value, ref _lastModified);
        }

        private bool _isInUse;

        [Ignore(true, true)]
        public bool IsInUse
        {
            get => _isInUse;
            set => this.SetWithNotify(value, ref _isInUse);
        }

    }
}
