// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils

using System.ComponentModel.DataAnnotations;
using CommunityToolkit.Mvvm.ComponentModel;

using EWSoftware.EntityFramework.DataAnnotations;

namespace AvaloniaTestApp.Database
{
    [LoadByKeyStoredProcedure("spProductInfo"), InsertEntityStoredProcedure("spProductAddUpdate"),
      UpdateEntityStoredProcedure("spProductAddUpdate"), DeleteEntityStoredProcedure("spProductDelete")]
    public sealed partial class ProductInfo : ObservableObject
    {
        // C# 14.0 or later allows us to use partial properties with the ObservableProperty attribute.
        [ObservableProperty, Key]
        public partial int ProductID { get; set; }

        [ObservableProperty]
        public partial string? ProductName { get; set; }

        [ObservableProperty]
        public partial string? CategoryName { get; set; }

        [ObservableProperty]
        public partial string? CompanyName { get; set; }

        [ObservableProperty]
        public partial string? QuantityPerUnit { get; set; }

        [ObservableProperty]
        public partial decimal UnitPrice { get; set; }

        [ObservableProperty]
        public partial short UnitsInStock { get; set; }

        [ObservableProperty]
        public partial short UnitsOnOrder { get; set; }

        [ObservableProperty]
        public partial short ReorderLevel { get; set; }

        [ObservableProperty]
        public partial bool Discontinued { get; set; }

        [ObservableProperty, Ignore(true, true)]
        public partial byte[] LastModified { get; set; } = [];
    }
}
