// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils

using EWSoftware.EntityFramework.DataAnnotations;

namespace AvaloniaTestApp.Database
{
    [NeverTrack, LoadAllStoredProcedure("spCategories")]
    public sealed class spCategoriesResult
    {
        public string CategoryName { get; set; } = null!;
    }
}
