// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils

using EWSoftware.EntityFramework.DataAnnotations;

namespace AvaloniaTestApp.Database
{
    [NeverTrack]
    public sealed class spProductSearchResult
    {
        public int ProductID { get; set; }

        public string? ProductName { get; set; }

        public string? CategoryName { get; set; }

        public string? CompanyName { get; set; }

        public decimal UnitPrice { get; set; }

        public bool Discontinued { get; set; }
    }
}
