// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils
//
// This code will need to be reviewed and tested to fix up any issues.

// TODO: Add or remove using statements as needed
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CommunityToolkit.Mvvm.ComponentModel;

using EWSoftware.EntityFramework;
using EWSoftware.EntityFramework.DataAnnotations;

namespace AvaloniaTestApp.Database
{
    [InsertEntityStoredProcedure("spDemoTableAddUpdate"), UpdateEntityStoredProcedure("spDemoTableAddUpdate"), DeleteEntityStoredProcedure("spDemoTableDelete")]
    public sealed partial class DemoTable : ObservableObject
    {
        [ObservableProperty]
        [property: Key]
        private int _listKey;

        [ObservableProperty]
        private string _label = String.Empty;

        [ObservableProperty]
        private string _textValue = String.Empty;

        [ObservableProperty]
        private DateTime _dateValue;

        [ObservableProperty]
        private bool _boolValue;

        [ObservableProperty]
        private System.Xml.Linq.XElement? _xmlValue;

        [ObservableProperty]
        private Guid? _guidValue;

        [ObservableProperty]
        private byte[]? _imageValue;

        [ObservableProperty]
        [property: Ignore(true, true)]
        private byte[] _lastModified = [];

    }
}
