// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils
//
// This code will need to be reviewed and tested to fix up any issues.

// TODO: Add or remove using statements as needed
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CommunityToolkit.Mvvm.ComponentModel;

using EWSoftware.EntityFramework;
using EWSoftware.EntityFramework.DataAnnotations;

namespace AvaloniaTestApp.Database
{
    [InsertEntityStoredProcedure("spProductAddUpdate"), UpdateEntityStoredProcedure("spProductAddUpdate"), DeleteEntityStoredProcedure("spProductDelete")]
    public sealed partial class ProductInfo : ObservableObject
    {
        [ObservableProperty]
        [property: Key]
        private int _productID;

        [ObservableProperty]
        private string? _productName;

        [ObservableProperty]
        private string? _categoryName;

        [ObservableProperty]
        private string? _companyName;

        [ObservableProperty]
        private string? _quantityPerUnit;

        [ObservableProperty]
        private decimal _unitPrice;

        [ObservableProperty]
        private short _unitsInStock;

        [ObservableProperty]
        private short _unitsOnOrder;

        [ObservableProperty]
        private short _reorderLevel;

        [ObservableProperty]
        private bool _discontinued;

        [ObservableProperty]
        [property: Ignore(true, true)]
        private byte[] _lastModified = [];

    }
}
