// Code generated by DBML To Entity Framework Converter tool
// https://github.com/EWSoftware/EntityFrameworkUtils
//
// This code will need to be reviewed and tested to fix up any issues.

// TODO: Add or remove using statements as needed
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CommunityToolkit.Mvvm.ComponentModel;

using EWSoftware.EntityFramework;
using EWSoftware.EntityFramework.DataAnnotations;

namespace AvaloniaTestApp.Database
{
    // TODO: Check \gh\EntityFrameworkUtils\LinqToSQLTestApp\Database\StateCode.cs for additional code for the entity
    [InsertEntityStoredProcedure("spStateCodeAddUpdate"), UpdateEntityStoredProcedure("spStateCodeAddUpdate"), DeleteEntityStoredProcedure("spStateCodeDelete")]
    public sealed partial class StateCode : ObservableObject
    {
        [ObservableProperty]
        private string _state = String.Empty;

        [ObservableProperty]
        private string _stateDesc = String.Empty;

        [ObservableProperty]
        [property: Key, Ignore(true, true)]
        private byte[] _lastModified = [];

        [ObservableProperty]
        [property: Ignore(true, true)]
        private bool _isInUse;

    }
}
