// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:EWSoftware.EntityFramework.DatabaseExtensions.CreateLoadCommand``1(Microsoft.EntityFrameworkCore.DbContext,System.Object[])~System.ValueTuple{System.Data.Common.DbConnection,System.Data.Common.DbCommand,System.Collections.Generic.Dictionary{System.String,System.Reflection.PropertyInfo},System.Boolean,System.Type}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:EWSoftware.EntityFramework.DatabaseExtensions.PrepareMethodCommand(Microsoft.EntityFrameworkCore.DbContext,System.Data.Common.DbCommand,System.Reflection.MethodInfo,System.Object[],System.String)~System.Collections.Generic.List{System.ValueTuple{System.String,System.Int32}}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:EWSoftware.EntityFramework.DatabaseExtensions.GetCommand(Microsoft.EntityFrameworkCore.DbContext,System.String,Microsoft.Data.SqlClient.SqlParameter[])~Microsoft.Data.SqlClient.SqlCommand")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:EWSoftware.EntityFramework.DatabaseExtensions.CreateInsertUpdateCommand``1(Microsoft.EntityFrameworkCore.DbContext,``0,System.Boolean)~System.ValueTuple{System.Data.Common.DbConnection,System.Data.Common.DbCommand,System.Collections.Generic.List{System.ValueTuple{System.Reflection.PropertyInfo,Microsoft.Data.SqlClient.SqlParameter}},System.Boolean}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:EWSoftware.EntityFramework.DatabaseExtensions.CreateDeleteCommand``1(Microsoft.EntityFrameworkCore.DbContext,``0)~System.ValueTuple{System.Data.Common.DbConnection,System.Data.Common.DbCommand,System.Boolean}")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:EWSoftware.EntityFramework.DatabaseExtensions.GetCommand(Microsoft.EntityFrameworkCore.DbContext,System.String,Microsoft.Data.SqlClient.SqlParameter[])~Microsoft.Data.SqlClient.SqlCommand")]
